# Generated by Django 4.2.23 on 2025-08-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Empleado',
        ),
    ]
