# Generated by Django 4.2.23 on 2025-08-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='category',
            field=models.ManyToManyField(to='erp.category'),
        ),
    ]
